version: '3.8'

services:
  crycat-bot:
    build: .
    container_name: crycat-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    ports:
      - "5000:5000"  # Webhook сервер
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - crycat-network

  nginx:
    image: nginx:alpine
    container_name: crycat-nginx
    restart: unless-stopped
    depends_on:
      - crycat-bot
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - crycat-network

networks:
  crycat-network:
    driver: bridge