blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/crycat/crycat-bot/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/crycat/crycat-bot/security/advisories
    about: Please report security vulnerabilities here.
  - name: Telegram Support
    url: https://t.me/crycat_support
    about: Get help via Telegram.